# coding: utf-8

"""
Mozart platform API

API for interacting with the Mozart platform.

The version of the OpenAPI document: 0.2.0
Contact: support@bang-olufsen.dk
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
)
from typing_extensions import Annotated, Self


class SoundAdjustments(BaseModel):
    """
    SoundAdjustments
    """  # noqa: E501

    advanced_beamforming: Annotated[
        Optional[StrictInt], Field(alias="advancedBeamforming")
    ] = None
    ambience: Optional[Union[StrictFloat, StrictInt]] = None
    bass: Optional[StrictInt] = None
    directivity: Optional[StrictStr] = None
    eco_mode: Annotated[Optional[StrictBool], Field(alias="ecoMode")] = None
    fadein: Optional[StrictBool] = None
    loudness: Optional[StrictBool] = None
    treble: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = [
        "advancedBeamforming",
        "ambience",
        "bass",
        "directivity",
        "ecoMode",
        "fadein",
        "loudness",
        "treble",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SoundAdjustments from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if directivity (nullable) is None
        # and model_fields_set contains the field
        if self.directivity is None and "directivity" in self.model_fields_set:
            _dict["directivity"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SoundAdjustments from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "advancedBeamforming": obj.get("advancedBeamforming"),
            "ambience": obj.get("ambience"),
            "bass": obj.get("bass"),
            "directivity": obj.get("directivity"),
            "ecoMode": obj.get("ecoMode"),
            "fadein": obj.get("fadein"),
            "loudness": obj.get("loudness"),
            "treble": obj.get("treble"),
        })
        return _obj
