# coding: utf-8

"""
Mozart platform API

API for interacting with the Mozart platform.

The version of the OpenAPI document: 0.2.0
Contact: support@bang-olufsen.dk
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

try:
    from pydantic.v1 import BaseModel, Field, StrictStr, constr, validator
except ImportError:
    from pydantic import BaseModel, Field, StrictStr, constr, validator


class SpeakerLinkRole(BaseModel):
    """
    SpeakerLinkRole
    """

    channel: Optional[StrictStr] = None
    desired: Optional[StrictStr] = None
    primary: Optional[constr(strict=True)] = Field(
        default=None, description="Speaker serial number"
    )
    role: StrictStr = Field(...)
    __properties = ["channel", "desired", "primary", "role"]

    @validator("channel")
    def channel_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in (
            "all",
            "any",
            "left",
            "right",
        ):
            raise ValueError(
                "must be one of enum values ('all', 'any', 'left', 'right')"
            )
        return value

    @validator("desired")
    def desired_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in (
            "none",
            "primary",
            "secondary",
        ):
            raise ValueError(
                "must be one of enum values ('none', 'primary', 'secondary')"
            )
        return value

    @validator("primary")
    def primary_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d{8}", value):
            raise ValueError(r"must validate the regular expression /^\d{8}/")
        return value

    @validator("role")
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value not in (
            "none",
            "primary",
            "secondary",
        ):
            raise ValueError(
                "must be one of enum values ('none', 'primary', 'secondary')"
            )
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SpeakerLinkRole:
        """Create an instance of SpeakerLinkRole from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SpeakerLinkRole:
        """Create an instance of SpeakerLinkRole from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SpeakerLinkRole.parse_obj(obj)

        _obj = SpeakerLinkRole.parse_obj(
            {
                "channel": obj.get("channel"),
                "desired": obj.get("desired"),
                "primary": obj.get("primary"),
                "role": obj.get("role"),
            }
        )
        return _obj
